# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouYuZB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouYuZB
  pod "Alamofire"

  target 'DouYuZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYuZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
